import { AppConfigType, FeatureType } from './types'

import Feature from '@/static/features/1.jpeg'
import Feature2 from '@/static/features/2.jpeg'
import Feature3 from '@/static/features/3.jpeg'
import Feature4 from '@/static/features/4.jpeg'
import Feature5 from '@/static/features/5.jpeg'
import Feature6 from '@/static/features/6.jpeg'
import Feature7 from '@/static/features/7.jpeg'
import Feature8 from '@/static/features/8.jpeg'
import Feature9 from '@/static/features/9.jpeg'
import Feature10 from '@/static/features/10.jpeg'
import Feature11 from '@/static/features/11.jpeg'
import Feature12 from '@/static/features/12.jpeg'
import Feature13 from '@/static/features/13.jpeg'

export const features: FeatureType[] = [
  {
    src: Feature,
    slug: 'grammar_correction',
    tags: ['Transformation', 'Generation'],
    title: 'Grammar correction',
    subtitle: 'Corrects sentences into standard English.',
    callToActionText: 'Start',
    label: 'Correct this to standard English:',
    settings: {
      model: 'text-davinci-003',
      max_tokens: 60,
      temperature: 0,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    src: Feature2,
    slug: 'questions_and_answears',
    tags: ['Answers', 'Generation', 'Conversation'],
    title: 'Q&A',
    subtitle: 'Answer questions based on existing knowledge.',
    callToActionText: 'Start',
    label:
      'I am a highly intelligent question answering bot. If you ask me a question that is rooted in truth, I will give you the answer. If you ask me a question that is nonsense, trickery, or has no clear answer, I will respond with "Unknown".',
    settings: {
      model: 'text-davinci-003',
      max_tokens: 100,
      temperature: 0,
      top_p: 1,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    src: Feature3,
    slug: 'summarization',
    tags: ['Transformation', 'Generation'],
    title: 'TL;DR summarization',
    subtitle: 'Summarize your very long text into a short summary.',
    callToActionText: 'Start',
    label: 'Summarize text below:',
    settings: {
      model: 'text-davinci-003',
      max_tokens: 60,
      temperature: 0.7,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 1,
    },
  },
  {
    src: Feature4,
    slug: 'product_ad_from_description',
    tags: ['Generation'],
    title: 'Ad from product description',
    subtitle: 'Turn a product description into ad copy.',
    callToActionText: 'Start',
    label:
      'Write a creative ad for the following product to run on Facebook aimed at parents: Product:',
    settings: {
      model: 'text-davinci-003',
      max_tokens: 100,
      temperature: 0.5,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    src: Feature5,
    slug: 'javascript_helper_chatbot',
    tags: ['Code', 'Answers', 'Conversation'],
    title: 'JavaScript chatbot',
    subtitle:
      'This is a message-style chatbot that can answer questions about using JavaScript. It uses a few examples to get the conversation started.',
    callToActionText: 'Start',
    label: 'JavaScript question:',
    settings: {
      model: 'text-davinci-003',
      max_tokens: 100,
      temperature: 0,
      top_p: 1.0,
      frequency_penalty: 0.5,
      presence_penalty: 0.0,
    },
  },
  {
    src: Feature6,
    slug: 'explain_code',
    tags: ['Code', 'Translation'],
    title: 'Explain code',
    subtitle: 'Explain a complicated piece of code.',
    callToActionText: 'Start',
    label: 'Explain code below:',
    settings: {
      model: 'text-davinci-003',
      max_tokens: 150,
      temperature: 0.5,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    src: Feature7,
    slug: 'mood_to_colors',
    tags: ['Transformation', 'Generation'],
    title: 'Mood to color',
    subtitle: 'Turn a text description into a color.',
    callToActionText: 'Start',
    label: 'Generate CSS code for a color in hex like a:',
    settings: {
      model: 'text-davinci-003',
      max_tokens: 60,
      temperature: 0.0,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    src: Feature8,
    slug: 'friendly_chat',
    tags: ['Conversation', 'Generation'],
    title: 'Friendly chat',
    subtitle: 'Emulate a text message conversation.',
    callToActionText: 'Start',
    label:
      'You: What have you been up to? Friend: Watching old movies. You: Did you watch anything interesting? Friend: Yeah, I watched an old classic called Casablanca. It was really good! You:',
    settings: {
      model: 'text-davinci-003',
      max_tokens: 60,
      temperature: 0.5,
      top_p: 1.0,
      frequency_penalty: 0.5,
      presence_penalty: 0.0,
      stop: ['You:'],
    },
  },
  {
    src: Feature9,
    slug: 'analogy_maker',
    tags: ['Generation'],
    title: 'Analogy maker',
    subtitle:
      'Create analogies. Modified from a community prompt to require fewer examples.',
    callToActionText: 'Start',
    label: 'Create an analogy for this phrase:',
    settings: {
      model: 'text-davinci-003',
      max_tokens: 60,
      temperature: 0.5,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    src: Feature10,
    slug: 'essay_outline',
    tags: ['Generation'],
    title: 'Essay outline',
    subtitle: 'Generate an outline for a research topic.',
    callToActionText: 'Start',
    label: 'Create an outline for an essay about:',
    settings: {
      model: 'text-davinci-003',
      max_tokens: 150,
      temperature: 0.3,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    src: Feature11,
    slug: 'study_notes',
    tags: ['Generation'],
    title: 'Create study notes',
    subtitle: 'Provide a topic and get study notes.',
    callToActionText: 'Start',
    label: 'What are 5 key points I should know when studying:',
    settings: {
      model: 'text-davinci-003',
      max_tokens: 150,
      temperature: 0.3,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
  {
    src: Feature12,
    slug: 'sarcastic_chat_bot',
    tags: ['Conversation', 'Generation'],
    title: 'Marv the sarcastic chat bot',
    subtitle: 'Marv is a factual chatbot that is also sarcastic.',
    callToActionText: 'Start',
    label:
      'Marv is a chatbot that reluctantly answers questions with sarcastic responses. Question:',
    settings: {
      model: 'text-davinci-003',
      max_tokens: 150,
      temperature: 0.5,
      top_p: 0.3,
      frequency_penalty: 0.5,
      presence_penalty: 0.0,
    },
  },
  {
    link: '/image_generation',
    src: Feature13,
    slug: 'image_generation_link',
    tags: ['Generation', 'Corrrection'],
    title: 'Image generation',
    subtitle: 'Generate image based on propmpt.',
    callToActionText: 'Generate',
    label: 'Generate hight quality image based on prompt:',
    settings: {
      model: 'text-davinci-003',
      max_tokens: 60,
      temperature: 0,
      top_p: 1.0,
      frequency_penalty: 0.0,
      presence_penalty: 0.0,
    },
  },
]

export const themes = {
  light: 'light',
  dark: 'dark',
  cupcake: 'cupcake',
  bumblebee: 'mblebee',
  emerald: 'emerald',
  corporate: 'rporate',
  synthwave: 'nthwave',
  retro: 'retro',
  cyberpunk: 'cyberpunk',
  valentine: 'valentine',
  halloween: 'helloween',
  garden: 'garden',
  forest: 'forest',
  aqua: 'aqua',
  lofi: 'lofi',
  pastel: 'pastel',
  fantasy: 'fantasy',
  wireframe: 'wireframe',
  black: 'black',
  luxury: 'luxury',
  dracula: 'dracula',
  cmyk: 'cmyk',
  autumn: 'autumn',
  business: 'business',
  acid: 'acid',
  lemonade: 'lemonade',
  night: 'night',
  coffee: 'coffee',
  winter: 'winter',
  dim: 'dim',
  nord: 'nord',
  sunset: 'sunset',
}

export const appConfig: AppConfigType = {
  iconSize: 'lg',
  iconWidth: 20,
  iconHeight: 20,
  defaultTheme: themes.dark,
}
